<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>TimerManager</AssemblyName>
    <RootNamespace>TimerManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="app.ico" />
    <EmbeddedResource Include="timer.mp3" />
  </ItemGroup>

</Project>
